name: OnTimeCommand
version: '${project.version}'
main: org.mscsmc.pureOnTimeCommand.OnTimeCommand
api-version: '1.21'
authors: [ VoyagerStar ]
description: '${project.description}'
website: '${project.url}'
icon: icon.png